{{- if and .Values.rbac.create (eq (include "clutta-scan.kubernetesEnabled" .) "true") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "clutta-scan.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end -}}
